dist: trusty
sudo: required
services:
    - docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
cache:
    directories:
        - node_modules
        - $HOME/gopath/pkg

language: go

os:
    - linux
    - osx

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master
env:
    global:
        - KIVIK_TEST_DSN_COUCH16="http://admin:abc123@localhost:6000/"
        - KIVIK_TEST_DSN_COUCH20="http://admin:abc123@localhost:6001/"
        - HOMEBREW_NO_AUTO_UPDATE=1
    matrix:
        - MODE=standard

matrix:
    allow_failures:
        - go: master
    include:
        - go: 1.9.x
          env: MODE=gopherjs
        - go: 1.9.x
          env: MODE=gopherjs
          os: osx
        - go: 1.9.x
          env: MODE=linter
        - go: 1.9.x
          env: MODE=coverage

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
