name: linter

on:
  push:
    branches: [main]
  pull_request:

env:
  GOLANGCI_LINT_VERSION: v2.7.2

jobs:
  golangcilint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Lint main module
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Validate generated sources
        run: |
          go generate ./...
          git diff --exit-code
      - name: Validate main go.mod
        run: |
          go mod tidy -compat=1.20 && git diff --exit-code
      - name: Lint x/sqlite module
        uses: golangci/golangci-lint-action@v8
        env:
          GOWORK: "off"
        with:
          working-directory: ./x/sqlite
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Validate x/sqlite go.mod
        env:
          GOWORK: "off"
        run: |
          cd x/sqlite && go mod tidy && git diff --exit-code
      - name: Lint x/pg module
        uses: golangci/golangci-lint-action@v8
        env:
          GOWORK: "off"
        with:
          working-directory: ./x/pg
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Validate x/pg go.mod
        env:
          GOWORK: "off"
        run: |
          cd x/pg && go mod tidy && git diff --exit-code
